#############################################################################
# Makefile for building: cuACS
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  cuACS.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile cuACS.pro -spec linux-g++ CONFIG+=debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cuACS1.0.0
DISTDIR = /home/student/Desktop/3004/3004/.tmp/cuACS1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		staffwindow.cpp \
		Animal.cpp \
		Bird.cpp \
		Cat.cpp \
		Client.cpp \
		Dog.cpp \
		Shelter.cpp \
		SmallAnimal.cpp \
		Staff.cpp \
		User.cpp \
		clientwindow.cpp \
		animalAddEditControl.cpp \
		animalViewControl.cpp \
		clientAddViewControl.cpp \
		clientEditControl.cpp \
		AnimalFactory.cpp \
		UserFactory.cpp \
		addStaffControl.cpp \
		clientListControl.cpp \
		animalListControl.cpp \
		mainWindow.cpp \
		ACMAlgorithm.cpp \
		matchListControl.cpp moc_staffwindow.cpp \
		moc_clientwindow.cpp \
		moc_animalAddEditControl.cpp \
		moc_animalViewControl.cpp \
		moc_clientAddViewControl.cpp \
		moc_clientEditControl.cpp \
		moc_addStaffControl.cpp \
		moc_clientListControl.cpp \
		moc_mainWindow.cpp \
		moc_animalListControl.cpp \
		moc_matchListControl.cpp
OBJECTS       = main.o \
		staffwindow.o \
		Animal.o \
		Bird.o \
		Cat.o \
		Client.o \
		Dog.o \
		Shelter.o \
		SmallAnimal.o \
		Staff.o \
		User.o \
		clientwindow.o \
		animalAddEditControl.o \
		animalViewControl.o \
		clientAddViewControl.o \
		clientEditControl.o \
		AnimalFactory.o \
		UserFactory.o \
		addStaffControl.o \
		clientListControl.o \
		animalListControl.o \
		mainWindow.o \
		ACMAlgorithm.o \
		matchListControl.o \
		moc_staffwindow.o \
		moc_clientwindow.o \
		moc_animalAddEditControl.o \
		moc_animalViewControl.o \
		moc_clientAddViewControl.o \
		moc_clientEditControl.o \
		moc_addStaffControl.o \
		moc_clientListControl.o \
		moc_mainWindow.o \
		moc_animalListControl.o \
		moc_matchListControl.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuACS.pro staffwindow.h \
		Animal.h \
		Cat.h \
		Client.h \
		Dog.h \
		Shelter.h \
		Staff.h \
		User.h \
		Bird.h \
		SmallAnimal.h \
		clientwindow.h \
		animalAddEditControl.h \
		animalViewControl.h \
		clientAddViewControl.h \
		clientEditControl.h \
		AbstractFactory.h \
		AnimalFactory.h \
		UserFactory.h \
		addStaffControl.h \
		clientListControl.h \
		mainWindow.h \
		animalListControl.h \
		ACMAlgorithm.h \
		matchListControl.h main.cpp \
		staffwindow.cpp \
		Animal.cpp \
		Bird.cpp \
		Cat.cpp \
		Client.cpp \
		Dog.cpp \
		Shelter.cpp \
		SmallAnimal.cpp \
		Staff.cpp \
		User.cpp \
		clientwindow.cpp \
		animalAddEditControl.cpp \
		animalViewControl.cpp \
		clientAddViewControl.cpp \
		clientEditControl.cpp \
		AnimalFactory.cpp \
		UserFactory.cpp \
		addStaffControl.cpp \
		clientListControl.cpp \
		animalListControl.cpp \
		mainWindow.cpp \
		ACMAlgorithm.cpp \
		matchListControl.cpp
QMAKE_TARGET  = cuACS
DESTDIR       = 
TARGET        = cuACS


first: all
####### Build rules

$(TARGET): ui_menu.h ui_animalDetailView.h ui_animalListView.h ui_clientDetailView.h ui_addStaffView.h ui_clientListView.h ui_mainWindow.h ui_matchDetailView.h ui_matchListView.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cuACS.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuACS.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile cuACS.pro -spec linux-g++ CONFIG+=debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
cuACS.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cuACS.pro -spec linux-g++ CONFIG+=debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents staffwindow.h Animal.h Cat.h Client.h Dog.h Shelter.h Staff.h User.h Bird.h SmallAnimal.h clientwindow.h animalAddEditControl.h animalViewControl.h clientAddViewControl.h clientEditControl.h AbstractFactory.h AnimalFactory.h UserFactory.h addStaffControl.h clientListControl.h mainWindow.h animalListControl.h ACMAlgorithm.h matchListControl.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp staffwindow.cpp Animal.cpp Bird.cpp Cat.cpp Client.cpp Dog.cpp Shelter.cpp SmallAnimal.cpp Staff.cpp User.cpp clientwindow.cpp animalAddEditControl.cpp animalViewControl.cpp clientAddViewControl.cpp clientEditControl.cpp AnimalFactory.cpp UserFactory.cpp addStaffControl.cpp clientListControl.cpp animalListControl.cpp mainWindow.cpp ACMAlgorithm.cpp matchListControl.cpp $(DISTDIR)/
	$(COPY_FILE) --parents menu.ui animalDetailView.ui animalListView.ui clientDetailView.ui addStaffView.ui clientListView.ui mainWindow.ui matchDetailView.ui matchListView.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_staffwindow.cpp moc_clientwindow.cpp moc_animalAddEditControl.cpp moc_animalViewControl.cpp moc_clientAddViewControl.cpp moc_clientEditControl.cpp moc_addStaffControl.cpp moc_clientListControl.cpp moc_mainWindow.cpp moc_animalListControl.cpp moc_matchListControl.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_staffwindow.cpp moc_clientwindow.cpp moc_animalAddEditControl.cpp moc_animalViewControl.cpp moc_clientAddViewControl.cpp moc_clientEditControl.cpp moc_addStaffControl.cpp moc_clientListControl.cpp moc_mainWindow.cpp moc_animalListControl.cpp moc_matchListControl.cpp
moc_staffwindow.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		staffwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include staffwindow.h -o moc_staffwindow.cpp

moc_clientwindow.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		ui_menu.h \
		clientwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include clientwindow.h -o moc_clientwindow.cpp

moc_animalAddEditControl.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		AnimalFactory.h \
		AbstractFactory.h \
		mainWindow.h \
		ui_animalDetailView.h \
		animalAddEditControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include animalAddEditControl.h -o moc_animalAddEditControl.cpp

moc_animalViewControl.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		ui_animalDetailView.h \
		animalViewControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include animalViewControl.h -o moc_animalViewControl.cpp

moc_clientAddViewControl.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		clientListControl.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		clientwindow.h \
		UserFactory.h \
		ui_clientDetailView.h \
		ui_clientListView.h \
		clientAddViewControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include clientAddViewControl.h -o moc_clientAddViewControl.cpp

moc_clientEditControl.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		clientListControl.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		clientwindow.h \
		UserFactory.h \
		ui_clientDetailView.h \
		ui_clientListView.h \
		clientEditControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include clientEditControl.h -o moc_clientEditControl.cpp

moc_addStaffControl.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		UserFactory.h \
		AbstractFactory.h \
		clientListControl.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		clientwindow.h \
		ui_clientDetailView.h \
		ui_clientListView.h \
		ui_addStaffView.h \
		addStaffControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include addStaffControl.h -o moc_addStaffControl.cpp

moc_clientListControl.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		clientListControl.h \
		ui_clientListView.h \
		clientwindow.h \
		UserFactory.h \
		ui_clientDetailView.h \
		clientListControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include clientListControl.h -o moc_clientListControl.cpp

moc_mainWindow.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainWindow.h -o moc_mainWindow.cpp

moc_animalListControl.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		ui_animalListView.h \
		animalListControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include animalListControl.h -o moc_animalListControl.cpp

moc_matchListControl.cpp: Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		ui_matchListView.h \
		matchListControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Desktop/3004/3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include matchListControl.h -o moc_matchListControl.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_menu.h ui_animalDetailView.h ui_animalListView.h ui_clientDetailView.h ui_addStaffView.h ui_clientListView.h ui_mainWindow.h ui_matchDetailView.h ui_matchListView.h
compiler_uic_clean:
	-$(DEL_FILE) ui_menu.h ui_animalDetailView.h ui_animalListView.h ui_clientDetailView.h ui_addStaffView.h ui_clientListView.h ui_mainWindow.h ui_matchDetailView.h ui_matchListView.h
ui_menu.h: menu.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic menu.ui -o ui_menu.h

ui_animalDetailView.h: animalDetailView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic animalDetailView.ui -o ui_animalDetailView.h

ui_animalListView.h: animalListView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic animalListView.ui -o ui_animalListView.h

ui_clientDetailView.h: clientDetailView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic clientDetailView.ui -o ui_clientDetailView.h

ui_addStaffView.h: addStaffView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic addStaffView.ui -o ui_addStaffView.h

ui_clientListView.h: clientListView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic clientListView.ui -o ui_clientListView.h

ui_mainWindow.h: mainWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainWindow.ui -o ui_mainWindow.h

ui_matchDetailView.h: matchDetailView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic matchDetailView.ui -o ui_matchDetailView.h

ui_matchListView.h: matchListView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic matchListView.ui -o ui_matchListView.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainWindow.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

staffwindow.o: staffwindow.cpp staffwindow.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalListControl.h \
		ui_animalListView.h \
		clientListControl.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		clientwindow.h \
		UserFactory.h \
		ui_clientDetailView.h \
		ui_clientListView.h \
		addStaffControl.h \
		ui_addStaffView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staffwindow.o staffwindow.cpp

Animal.o: Animal.cpp Animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Animal.o Animal.cpp

Bird.o: Bird.cpp Bird.h \
		Animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bird.o Bird.cpp

Cat.o: Cat.cpp Cat.h \
		Animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cat.o Cat.cpp

Client.o: Client.cpp Client.h \
		User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Client.o Client.cpp

Dog.o: Dog.cpp Dog.h \
		Animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dog.o Dog.cpp

Shelter.o: Shelter.cpp Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shelter.o Shelter.cpp

SmallAnimal.o: SmallAnimal.cpp SmallAnimal.h \
		Animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SmallAnimal.o SmallAnimal.cpp

Staff.o: Staff.cpp Staff.h \
		User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Staff.o Staff.cpp

User.o: User.cpp User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

clientwindow.o: clientwindow.cpp clientwindow.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		ui_menu.h \
		animalListControl.h \
		ui_animalListView.h \
		clientListControl.h \
		staffwindow.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		UserFactory.h \
		ui_clientDetailView.h \
		ui_clientListView.h \
		clientEditControl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientwindow.o clientwindow.cpp

animalAddEditControl.o: animalAddEditControl.cpp animalAddEditControl.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		AnimalFactory.h \
		AbstractFactory.h \
		mainWindow.h \
		ui_animalDetailView.h \
		animalListControl.h \
		ui_animalListView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animalAddEditControl.o animalAddEditControl.cpp

animalViewControl.o: animalViewControl.cpp animalViewControl.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		ui_animalDetailView.h \
		animalListControl.h \
		ui_animalListView.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animalViewControl.o animalViewControl.cpp

clientAddViewControl.o: clientAddViewControl.cpp clientAddViewControl.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		clientListControl.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		ui_clientListView.h \
		clientwindow.h \
		UserFactory.h \
		ui_clientDetailView.h \
		animalListControl.h \
		ui_animalListView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientAddViewControl.o clientAddViewControl.cpp

clientEditControl.o: clientEditControl.cpp clientEditControl.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		clientListControl.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		clientwindow.h \
		UserFactory.h \
		ui_clientDetailView.h \
		ui_clientListView.h \
		animalListControl.h \
		ui_animalListView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientEditControl.o clientEditControl.cpp

AnimalFactory.o: AnimalFactory.cpp AnimalFactory.h \
		AbstractFactory.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		User.h \
		Staff.h \
		Client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalFactory.o AnimalFactory.cpp

UserFactory.o: UserFactory.cpp UserFactory.h \
		AbstractFactory.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		User.h \
		Staff.h \
		Client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserFactory.o UserFactory.cpp

addStaffControl.o: addStaffControl.cpp addStaffControl.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		UserFactory.h \
		AbstractFactory.h \
		clientListControl.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		clientwindow.h \
		ui_clientDetailView.h \
		ui_clientListView.h \
		ui_addStaffView.h \
		animalListControl.h \
		ui_animalListView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addStaffControl.o addStaffControl.cpp

clientListControl.o: clientListControl.cpp clientListControl.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		clientAddViewControl.h \
		clientwindow.h \
		UserFactory.h \
		ui_clientDetailView.h \
		ui_clientListView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientListControl.o clientListControl.cpp

animalListControl.o: animalListControl.cpp animalListControl.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		mainWindow.h \
		ui_animalListView.h \
		staffwindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		clientwindow.h \
		animalAddEditControl.h \
		AnimalFactory.h \
		AbstractFactory.h \
		ui_animalDetailView.h \
		animalViewControl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animalListControl.o animalListControl.cpp

mainWindow.o: mainWindow.cpp mainWindow.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		ui_mainWindow.h \
		staffwindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		clientwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o mainWindow.cpp

ACMAlgorithm.o: ACMAlgorithm.cpp ACMAlgorithm.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ACMAlgorithm.o ACMAlgorithm.cpp

matchListControl.o: matchListControl.cpp matchListControl.h \
		Shelter.h \
		Staff.h \
		User.h \
		Client.h \
		Animal.h \
		Dog.h \
		Cat.h \
		Bird.h \
		SmallAnimal.h \
		staffwindow.h \
		mainWindow.h \
		ui_menu.h \
		ACMAlgorithm.h \
		ui_matchListView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matchListControl.o matchListControl.cpp

moc_staffwindow.o: moc_staffwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_staffwindow.o moc_staffwindow.cpp

moc_clientwindow.o: moc_clientwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientwindow.o moc_clientwindow.cpp

moc_animalAddEditControl.o: moc_animalAddEditControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animalAddEditControl.o moc_animalAddEditControl.cpp

moc_animalViewControl.o: moc_animalViewControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animalViewControl.o moc_animalViewControl.cpp

moc_clientAddViewControl.o: moc_clientAddViewControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientAddViewControl.o moc_clientAddViewControl.cpp

moc_clientEditControl.o: moc_clientEditControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientEditControl.o moc_clientEditControl.cpp

moc_addStaffControl.o: moc_addStaffControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addStaffControl.o moc_addStaffControl.cpp

moc_clientListControl.o: moc_clientListControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientListControl.o moc_clientListControl.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

moc_animalListControl.o: moc_animalListControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animalListControl.o moc_animalListControl.cpp

moc_matchListControl.o: moc_matchListControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_matchListControl.o moc_matchListControl.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

